baseURL = "http://github.com/"
languageCode = "en-us"
title = "My New Hugo Site"
pygmentsUseClasses=true
pygmentsOptions= "linenos=table, startinline=true"
pygmentsCodefencesGuessSyntax=true

[permalinks]
  post = ":title/"
